### PR TITLE
Update

### PR DESCRIPTION
**Pull request by vweevers**
Use level, drop 0.12, tweak readme. Closes #79, #80, #81, #82, #83, #84.

### CODE REVIEW

**Comment by vweevers** [comment]
I hoped I could make it use prebuilds, but the `postinstall` script doesn't work on linux. Is there a best practice for this? How about `"postinstall": "electron-rebuild -w leveldown"`?

**Comment by vweevers** [comment]
And.. `electron-rebuild` doesn't support node 4 😅

**Comment by ralphtheninja** [comment]
> And.. electron-rebuild doesn't support node 4

I'd just remove node 4 from travis. This is only a demo after all to show how level can be used.

**Comment by vweevers** [comment]
@ralphtheninja done, tests passing.

**Comment by vweevers** [comment]
I'm merging this, to close a whole bunch of issues. I'm assuming you approved the rest @ralphtheninja.

**Pull request merged**
